const actionTypes={
    USER_INFO_CHECK:"USER_INFO_CHECK",
    FETCH_USERS_START:"FETCH_USERS_START",
    FETCH_USERS_SUCCESS:"FETCH_USERS_SUCCESS",
    FETCH_USERS_FAIL:"FETCH_USERS_FAIL",
    LOGIN_SUCCESS:"LOGIN_SUCCESS",
    LOGOUT:"LOGOUT"
}

export default actionTypes